# 课程目录服务配置
# Data ID: catalog-service.yml
# Group: COURSEHUB_GROUP
# Namespace: dev

app:
  name: catalog-service
  description: 课程目录服务
  version: 1.0.0

feature:
  cache:
    enabled: true
    ttl: 600
  search:
    enabled: true
    max-results: 100

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/catalog_db?useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      connection-timeout: 30000
