# 选课服务配置
# Data ID: enrollment-service.yml
# Group: COURSEHUB_GROUP
# Namespace: dev

app:
  name: enrollment-service
  description: 选课服务
  version: 1.0.0

feature:
  enrollment-limit:
    enabled: true
    max-courses-per-student: 10
  waitlist:
    enabled: true
    max-size: 50

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/enrollment_db?useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      connection-timeout: 30000

# 外部服务配置
services:
  user:
    url: http://localhost:8081
  catalog:
    url: http://localhost:8082
