# 用户服务配置
# Data ID: user-service.yml
# Group: COURSEHUB_GROUP
# Namespace: dev

app:
  name: user-service
  description: 用户服务
  version: 1.0.0

# 功能开关配置
feature:
  new-ui:
    enabled: false
  cache:
    enabled: true
    ttl: 300
  rate-limit:
    enabled: true
    max-requests: 100

# 数据库配置（可以从共享配置中覆盖）
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
